  
#  This is component yaml spec template file.
#  Please replace all '< ... >' to define your own component.
#  For more details, please refer to https://aka.ms/azure-ml-component-specs
$schema: http://azureml/sdk-2-0/CommandComponent.json
name: ProduceTinyImagenet200
version: 0.0.1
display_name: ProduceTinyImagenet200
type: CommandComponent
is_deterministic: false
tags:
  azureml.Designer : true
inputs:
  OriginalZip:
    type: ZipFile
    optional: false
    description: original tiny-imagenet-200 zip file
outputs:
  Train:
    type: ImageDirectory
  Validation:
    type: ImageDirectory
  Test:
    type: ImageDirectory
command: >-
  python ProduceTinyImagenet200.py 
  --OriginalZip {inputs.OriginalZip} 
  --Train {outputs.Train} --Validation {outputs.Validation} --Test {outputs.Test} 
environment:
  docker:
    image: mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04
  conda:
    conda_dependencies:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.7.6
      - pip=20.2
      - pip:
        - azureml-sdk==0.1.0.*
        - azureml-designer-core==0.0.54
        - azureml-dataset-runtime[fuse,pandas]
        - --index-url https://azuremlsdktestpypi.azureedge.net/dev/aml/office/134157926D8F
        - --extra-index-url https://pypi.org/simple
        - < Specify your extra dependencies >
  os: Linux
